#!/usr/bin/env python

from distutils.core import Extension, setup

dcm_module = Extension(
    "_dcm",
    sources=[
        "DcmAlgorithm_wrap.cxx",
        "DcmAlgorithm.cpp",
    ],  # fib_wrap.cxx is going to be generated by swig
)

setup(
    name="DcmAlgorithm",
    version="0.0",
    author="Ng Wei Jie, Brandon",
    description="dcm algorithm",
    ext_modules=[dcm_module],
    py_modules=["dcm"],  # name of module that we're going import
)
